### PR TITLE
Added ability to use AF_PACKET socket

### PR DESCRIPTION
**Pull request by eyakubovich**
Using AF_PACKET is necessary to:
(a) allow bcast traffic to go thru rp_filter enabled
(b) ability to not use Broadcast flag and get packets
unicasted back.

### CODE REVIEW

**Comment by d2g** [comment]
Thanks.

I'll review and get back to you.

**Comment by d2g** [comment]
For Reference:
Extra info around the syscall package - https://golang.org/s/go1.4-syscall

**Comment by d2g** [comment]
I've pushed this to a separate branch (af_packet-sock) as I'm unable to see if it even build on Linux ( Windows Desktop :( ) I'll test later as some stage but I've changed the API so that you should find:

s, err := dhcp4client.NewPacketSock(10)
...
c, err := dhcp4client.New(dhcp4client.HardwareAddr(m),dhcp4client.Connection(s))
...

Works.

**Comment by eyakubovich** [comment]
I like the changes. I didn't want to break the existing API but if that's ok, this cleans it up. I also realized that why I had a build tag on pktsock.go, there was nothing to disable ConnectPacket() function so it probably failed on non-Linux systems.

**Comment by d2g** [comment]
Let me know if you want me to version 1 this release and I'll start making sure I don't make any api changes within this version.

**Pull request closed without merging**
